const List<Map<String, dynamic>> fieldMockData = [
  {
    "id": 1,
    "name": "Stadium Alpha",
    "address": "123 Alpha Way",
    "description": "Large field suitable for soccer.",
    "phone_number": "555-123-4567",
    "area_id": 1,
    "size": 5000,
    "rating": 4.8,
    "status": 1,
  },
  {
    "id": 2,
    "name": "Stadium Beta",
    "address": "456 Beta Lane",
    "description": "Medium field suitable for practice.",
    "phone_number": "555-987-6543",
    "area_id": 1,
    "size": 3000,
    "rating": 4.5,
    "status": 1,
  },
  {
    "id": 3,
    "name": "City Center Field",
    "address": "321 Center Ave",
    "description": "Convenient location for evening matches.",
    "phone_number": "555-654-3210",
    "area_id": 2,
    "size": 4500,
    "rating": 4.6,
    "status": 1,
  },
  {
    "id": 4,
    "name": "West End Arena",
    "address": "789 Pine Ave",
    "description": "Newly renovated field for tournaments.",
    "phone_number": "555-789-1234",
    "area_id": 3,
    "size": 6000,
    "rating": 4.9,
    "status": 1,
  },
];
