server:
  port: 9001
  servlet:
    context-path: /stadium-service

spring:
  application:
    name: stadium-service
  config:
    import: configserver:http://localhost:9296
  datasource:

    url: jdbc:mysql://${DB_HOST:localhost}:3306/project_s4
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
config:
  url:
    payment-service-url: "${endpoint_payment_service:http://localhost:9007/payment-service}"
    booking-service-url: "${endpoint_booking_service:http://localhost:9002/booking-service}"

aws:
  s3:
    bucketName: projectsem4
    accessKey: AKIAYSWVGI4FTSIJFW5O
    secretKey: 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

