version: '3'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak_web
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://localhost:3307/keycloakdb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 7080:8080

#  keycloakdb:
#    image: mysql
#    container_name: keycloakdb
#    volumes:
#      - mysql_data:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: keycloakdb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - 3307:3306
#
#volumes:
#  mysql_data:
